---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-yaml
    - id: debug-statements
      files: src/rpo|tests
      types: [python]

- repo: https://github.com/fpgmaas/deptry.git
  rev: "0.23.0"
  hooks:
    - id: deptry
      args: ["--ignore", "DEP001"]
